CREATE TABLE AssetGroup(
	_id INTEGER PRIMARY KEY NOT NULL,
	Name TEXT(50) NOT NULL UNIQUE,
	Description TEXT(255) NULL,
	Active BIT NOT NULL DEFAULT 1
);

CREATE TABLE Asset(
	_id INTEGER PRIMARY KEY NOT NULL,
	Name TEXT(50) NOT NULL,
	Description TEXT(255) NULL,
	Label TEXT(30) NOT NULL UNIQUE,
	Active BIT NOT NULL DEFAULT 1,
	PurchaseDate date NULL,
	AssetGroupId INTEGER NULL,
	FOREIGN KEY(AssetGroupId) REFERENCES AssetGroup(_id)
);	

CREATE TABLE Role(
	_id INTEGER PRIMARY KEY NOT NULL,
	RoleName TEXT(80) NOT NULL UNIQUE,
	Privileges INTEGER NULL
);

CREATE TABLE User(
	_id INTEGER PRIMARY KEY NOT NULL,
	FullName TEXT(60) NULL,
	UserName TEXT(30) NOT NULL,
	Email TEXT(50) NOT NULL,
	Password TEXT(256) NOT NULL,
	OIB TEXT(11) NULL,
	RoleId INTEGER NOT NULL,
	FOREIGN KEY(RoleId) REFERENCES Role(_id)	
);

CREATE TABLE UserAgreement(
	_id INTEGER PRIMARY KEY NOT NULL,
	Status TEXT(10) NOT NULL,
	DocumentURL TEXT(255) NULL,
	UserId INTEGER NOT NULL,
	FOREIGN KEY(UserId) REFERENCES User(_id)
);

CREATE TABLE UserAgreementAsset(
	_id INTEGER PRIMARY KEY NOT NULL,
	AssetId INTEGER NOT NULL UNIQUE,
	UserAgreementId INTEGER NOT NULL,
	FOREIGN KEY(AssetId) REFERENCES Asset(_id),
	FOREIGN KEY(UserAgreementId) REFERENCES UserAgreement(_id)
);